export default [
  {
    description: "The account cannot be initialized because it is already being used..",
    name: "AlreadyInUse"
  },
  {
    description: "The program address provided doesn't match value generated by the program..",
    name: "InvalidProgramAddress"
  },
  {
    description: "The deserialization of the Token state returned something besides State::Token..",
    name: "ExpectedMint"
  },
  {
    description: "The deserialization of the Token state returned something besides State::Account..",
    name: "ExpectedAccount"
  },
  {
    description: "The coin vault provided doesn't match the coin vault in the AmmInfo..",
    name: "InvalidCoinVault"
  },

// 5
  {
    description: "The pc vault provided doesn't match the pc vault in the AmmInfo..",
    name: "InvalidPCVault"
  },
  {
    description: "The token_lp provided doesn't match the token_lp in the AmmInfo..",
    name: "InvalidTokenLP"
  },
  {
    description: "The dest_token_coin provided doesn't match the dest_token_coin in WithdrawTokenInfo..",
    name: "InvalidDestTokenCoin"
  },
  {
    description: "The dest_token_pc provided doesn't match the dest_token_pc in WithdrawTokenInfo..",
    name: "InvalidDestTokenPC"
  },
  {
    description: "The pool_mint provided doesn't match the pool_mint in the AmmInfo..",
    name: "InvalidPoolMint"
  },

// 10
  {
    description: "The open_orders provided doesn't match the open_orders in in the AmmInfo..",
    name: "InvalidOpenOrders"
  },
  {
    description: "The market provided doesn't match the market in the AmmInfo..",
    name: "InvalidMarket"
  },
  {
    description: "The market program provided doesn't match the market program in the AmmInfo..",
    name: "InvalidMarketProgram"
  },
  {
    description: "The target_orders provided doesn't match the target_orders in the AmmInfo..",
    name: "InvalidTargetOrders"
  },
  {
    description: "The Account provided must be writeable..",
    name: "AccountNeedWriteable"
  },

// 15
  {
    description: "The Account provided must be readonly..",
    name: "AccountNeedReadOnly"
  },
  {
    description: "The token_coin's mint provided doesn't match the coin_mint's key..",
    name: "InvalidCoinMint"
  },
  {
    description: "The token_pc's mint provided doesn't match the pc_mint's key..",
    name: "InvalidPCMint"
  },
  {
    description: "The owner of the input isn't set to the program address generated by the program..",
    name: "InvalidOwner"
  },
  {
    description: "The initialized pool had a non zero supply..",
    name: "InvalidSupply"
  },

// 20
  {
    description: "The initialized token has a delegate..",
    name: "InvalidDelegate"
  },
  {
    description: "Invalid Sign Account.",
    name: "Invalid Sign Account"
  },
  {
    description: "The amm status is invalid..",
    name: "InvalidStatus"
  },
  {
    description: "Invalid instruction number passed in.",
    name: "Invalid instruction"
  },
  {
    description: "The number of account provided does not match the expectations.",
    name: "Wrong accounts number"
  },

// 25
  {
    description: "The target account owner is not match with this program.",
    name: "The target account owner is not match with this program"
  },
  {
    description: "The owner saved in target is not match with this amm pool.",
    name: "The owner saved in target is not match with this amm pool"
  },
  {
    description: "The amm account owner is not match with this program.",
    name: "The amm account owner is not match with this program"
  },
  {
    description: "The params set is invalid.",
    name: "Params Set is invalid"
  },
  {
    description: "The params input is invalid..",
    name: "InvalidInput"
  },

// 30
  {
    description: "instruction exceeds desired slippage limit.",
    name: "instruction exceeds desired slippage limit"
  },
  {
    description: "The calculation exchange rate failed..",
    name: "CalculationExRateFailure"
  },
  {
    description: "Checked_Sub Overflow",
    name: "Checked_Sub Overflow"
  },
  {
    description: "Checked_Add Overflow.",
    name: "Checked_Add Overflow"
  },
  {
    description: "Checked_Mul Overflow.",
    name: "Checked_Mul Overflow"
  },

// 35
  {
    description: "Checked_Div Overflow.",
    name: "Checked_Div Overflow"
  },
  {
    description: "Empty Funds.",
    name: "Empty Funds"
  },
  {
    description: "Calc pnl error.",
    name: "Calc pnl error"
  },
  {
    description: "InvalidSplTokenProgram.",
    name: "InvalidSplTokenProgram"
  },
  {
    description: "TakePnlError.",
    name: "Take Pnl error"
  },

// 40
  {
    description: "Insufficient funds.",
    name: "Insufficient funds"
  },
  {
    description: "ConversionFailure.",
    name: "Conversion to u64 failed with an overflow or underflow"
  },
  {
    description: "The user token input does not match amm.",
    name: "user token input does not match amm"
  },
  {
    description: "The srm_token's mint provided doesn't match the pc_mint's key.",
    name: "InvalidSrmMint"
  },
  {
    description: "The srm_token provided doesn't match the srm_token in the program",
    name: "InvalidSrmToken"
  },

// 45
  {
    description: "TooManyOpenOrders.",
    name: "TooManyOpenOrders"
  },
  {
    description: "OrderAtSlotIsPlaced.",
    name: "OrderAtSlotIsPlaced"
  },
  {
    description: "InvalidSysProgramAddress.",
    name: "InvalidSysProgramAddress"
  },
  {
    description: "The provided fee does not match the program owner's constraints.",
    name: "The provided fee does not match the program owner's constraints"
  },
  {
    description: "Repeat create amm about market.",
    name: "Repeat create amm about market"
  },

// 50
  {
    description: "Not allow Zero LP.",
    name: "Not allow Zero LP"
  },
  {
    description: "The provided token account has a close authority..",
    name: "Token account has a close authority"
  },
  {
    description: "The pool token mint has a freeze authority..",
    name: "Pool token mint has a freeze authority"
  },
  {
    description: "The referrer_pc_wallet's mint provided doesn't match the pc_mint's key..",
    name: "InvalidReferPCMint"
  },
  {
    description: "InvalidConfigAccount.",
    name: "InvalidConfigAccount"
  },

// 55
  {
    description: "RepeatCreateConfigAccount.",
    name: "Repeat create config account"
  },
  {
    description: "MarketLotSizeIsTooLarge.",
    name: "Market lotSize is too large"
  },
  {
    description: "Init lp amount is too less..",
    name: "Init lp amount is too less(Because 10**lp_decimals amount lp will be locked)"
  },
  {
    description: "Unknown Amm Error.",
    name: "Unknown Amm Error"
  },
];